spring:
  profiles:
    default: dev
  application:
    name: popp-server
  config:
    import:
      - "classpath:contact-based-scenarios.yaml"
      - "classpath:open-egk-scenarios.yaml"
      - "classpath:contact-less-scenarios.yaml"

  datasource:
    url: jdbc:postgresql://localhost:5432/egk_hash_db
    username: poppserver
    password: verysafe
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:mykeystore.p12
    key-store-password: popp-store
    key-alias: ZertifikatAlias
    protocol: TLS
    enabled-protocols: TLSv1.2
jwt-token:
  popp:
    actor-id: "telematik-id"
    actor-profession-oid: "1.2.276.0.76.4.50"
    authorization-details: "details"
  connector:
    typ: "JWT"
