spring:
  config:
    import:
      - "classpath:contact-based-scenarios.yaml"
      - "classpath:open-egk-scenarios.yaml"
      - "classpath:contact-less-scenarios.yaml"
  profiles:
    default: dev
    active: dev

server:
  port: 8081
  tomcat:
    max-http-form-post-size: 2147483648 # 2GB

springdoc:
  api-docs:
    enabled: true

popp-server:
  url: wss://localhost:8443/ws
popp-client:
  secure:
    key-store: mykeystore.p12
    store-password: popp-store

connector:
  end-point-url: "https://localhost:9443/"
#  event-service-endpoint: https://localhost:9443/services/EventService/v7.2
#  terminal-configuration:
#    context:
#      clientSystemId: "Client-System"
#      workplaceId: "Arbeitsplatz_01"
#      principalId: "Client007"

card-reader:
  name:

virtual-card:
  image-file:
