popp-client:
  secure:
    key-store: mykeystore.p12
    store-password: popp-store
popp-server:
  url: wss://localhost:8443/ws

connector:
  end-point-url: "https://localhost:9443"
  log-ws: true
  secure:
    enable: true
    hostname-validation: false
    keystore: keystore.p12
    keystore-password: changeit
    trust-all: true
    truststore: truststore.p12
    truststore-password: changeit
  terminal-configuration:
    context:
      clientSystemId: "ClientID1"
      workplaceId: "Workplace1"
      mandantId: "Mandant1"
  soap-services:
    get-cards: "http://ws.gematik.de/conn/EventService/v7.2#GetCards"
    start-card-session: "http://ws.gematik.de/conn/CardService/v8.2#StartCardSession"
    stop-card-session: "http://ws.gematik.de/conn/CardService/v8.2#StopCardSession"
    secure-send-apdu: "http://ws.gematik.de/conn/CardService/v8.2#SecureSendAPDU"

card-reader:
  name: "Identive Identive CLOUD 4700 F Dual Interface Reader"
