connector:
  end-point-url: "https://127.0.0.1"
  log-ws: true
  secure:
    enable: true
    hostname-validation: false
    keystore: keystore.p12
    keystore-password: changeit
    trust-all: false
    truststore: truststore.p12
    truststore-password: changeit
  terminal-configuration:
    context:
      clientSystemId: "ClientID1"
      workplaceId: "Workplace1"
      mandantId: "Mandant1"

card-reader:
  name: "REINER SCT"

virtual-card:
  image-file: "IMG_eGK_G21_TU_root6 1.xml"

popp-client:
  static-qr:
    tid: "1-20-ARV1661246300001992"
    wpid: ""
    size: 300
