services:
  popp-server:
    build:
      context: ../popp-server
      dockerfile: docker/Dockerfile
    image: local/popp/popp-server:1.0.3
    container_name: popp-server
    ports:
      - "8443:8443"
    environment:
      - IDENTITIES_LOCATION=classpath:identities
      - CERT_HASH_IMPORT_LOCATION=file:/app/import
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/egk_hash_db
    networks:
      - popp-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: popp-postgres
    environment:
      POSTGRES_USER: poppserver
      POSTGRES_PASSWORD: verysafe
      POSTGRES_DB: egk_hash_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - popp-network

volumes:
  postgres_data:
    driver: local

networks:
  popp-network:
    driver: bridge
