services:
  popp-server-db:
    image: postgres:18-alpine
    container_name: popp-server-db
    environment:
      POSTGRES_USER: poppserver
      POSTGRES_PASSWORD: verysafe
      POSTGRES_DB: egk_hash_db
    ports:
      - "5432:5432"
    volumes:
      - popp-server-db-data:/var/lib/postgresql
    restart: on-failure
    networks:
      - popp-network

volumes:
  popp-server-db-data:

networks:
  popp-network:
    name: popp-network
    driver: bridge
